# Makefile generated by the project manager
#


# GENERATED: Fri Jan 02 16:46:05 +0800 2015
# DO NOT EDIT - file is regenerated whenever the project changes


## core information

ifeq ($(wildcard Makefile.mk),)
PRJ_DIR        = ..
else
PRJ_DIR        = .
endif
PRJ_FILE       = zynq.wpj
PRJ_FULL_PATH  = $(WIND_HOME)/workspace/zynq
PRJ_TYPE       = vxWorks
PRJ_OBJS       = sysALib.o sysLib.o usrAppInit.o usrRtpAppInit.o prjConfig.o linkSyms.o fifo.o PlcSpiTest.o comtest.o pulsetest.o
PRJ_MAKEFILE   = $(PRJ_DIR)/Makefile.mk
BOOT_OBJS      = romInit.o romStart.o $(BOOT_EXTRA)
BUILD_SPEC     = default
BSP_DIR        = $(TGT_DIR)/config/xlnx_zynq7k
VSB_DIR        = $(TGT_DIR)/lib
TGT_DIR        = $(WIND_BASE)/target



## set searching directories for dependencies

vpath %.c $(BSP_DIR)
vpath %.cpp $(BSP_DIR)
vpath %.cxx $(BSP_DIR)
vpath %.s $(BSP_DIR)


## build-configuration info

CPU            = ARMARCH7
TOOL           = diab
TOOL_FAMILY    = diab
ifeq ($(BUILD_SPEC),default)
DEFAULT_RULE   = vxWorks
endif

ifeq ($(BUILD_SPEC),default_rom)
DEFAULT_RULE   = vxWorks_rom
endif

ifeq ($(BUILD_SPEC),default_romCompress)
DEFAULT_RULE   = vxWorks_romCompress
endif

ifeq ($(BUILD_SPEC),default_romResident)
DEFAULT_RULE   = vxWorks_romResident
endif


## Memory adresses variables

RAM_LOW_ADRS = 200000
RAM_HIGH_ADRS = 1000000
LOCAL_MEM_LOCAL_ADRS = 00100000
DATA_SEG_ALIGN = 1
LOCAL_UNMAPPED_BASE_ADRS = 82000000
LOCAL_MEM_PHYS_ADRS = 20000000

## component-configuration info

COMPONENTS = DRV_ARM_GIC \
	DRV_ARM_MPCORE_TIMER \
	DRV_I2CBUS_ZYNQ7K \
	DRV_I2C_GENERIC_DEV \
	DRV_MMCSTORAGE_CARD \
	DRV_SIO_NS16550 \
	DRV_SIO_ZYNQ7K \
	DRV_SPIBUS_ZYNQ7K \
	DRV_SPI_GENERIC_DEV \
	DRV_VXBEND_ZYNQMAC \
	DRV_ZYNQ_SDHC_CTRL \
	INCLUDE_ADR_SPACE_LIB \
	INCLUDE_ADR_SPACE_SHELL_CMD \
	INCLUDE_ADR_SPACE_SHOW \
	INCLUDE_AIM_MMU_SHOW \
	INCLUDE_ANSI_ABORT \
	INCLUDE_ANSI_ABS \
	INCLUDE_ANSI_ASSERT \
	INCLUDE_ANSI_ATOF \
	INCLUDE_ANSI_BSEARCH \
	INCLUDE_ANSI_CTYPE \
	INCLUDE_ANSI_LOCALE \
	INCLUDE_ANSI_LONGJMP \
	INCLUDE_ANSI_MATH \
	INCLUDE_ANSI_MEMCHR \
	INCLUDE_ANSI_MEMCMP \
	INCLUDE_ANSI_MEMCPY \
	INCLUDE_ANSI_MEMMOVE \
	INCLUDE_ANSI_MEMSET \
	INCLUDE_ANSI_STDIO \
	INCLUDE_ANSI_STDIO_EXTRA \
	INCLUDE_ANSI_STDLIB \
	INCLUDE_ANSI_STDLIB_NUMBERS \
	INCLUDE_ANSI_STRCASECMP \
	INCLUDE_ANSI_STRCAT \
	INCLUDE_ANSI_STRCMP \
	INCLUDE_ANSI_STRCPY \
	INCLUDE_ANSI_STRDUP \
	INCLUDE_ANSI_STRERROR \
	INCLUDE_ANSI_STRING \
	INCLUDE_ANSI_STRLCPY \
	INCLUDE_ANSI_STRLEN \
	INCLUDE_ANSI_STRNCASECMP \
	INCLUDE_ANSI_STRNCAT \
	INCLUDE_ANSI_STRNCMP \
	INCLUDE_ANSI_STRNCPY \
	INCLUDE_ANSI_STRTOD \
	INCLUDE_ANSI_TIME \
	INCLUDE_APPL_LOG_UTIL \
	INCLUDE_ARM_INTRINSIC_VFP_MATH \
	INCLUDE_ATOMIC_OPERATORS \
	INCLUDE_AUX_CLK \
	INCLUDE_AVL_TREES \
	INCLUDE_AVL_UINT_TREES \
	INCLUDE_BASE_KERNEL \
	INCLUDE_BLIB \
	INCLUDE_BLIB_ARCH \
	INCLUDE_BMPLIB \
	INCLUDE_BOOT_HW_INIT \
	INCLUDE_BOOT_LINE_INIT \
	INCLUDE_BSP_MACROS \
	INCLUDE_CACHE_ENABLE \
	INCLUDE_CACHE_SUPPORT \
	INCLUDE_CHECKSUM \
	INCLUDE_CLASS_LIB \
	INCLUDE_CLASS_LIST \
	INCLUDE_CLASS_SHOW \
	INCLUDE_COMMON_NET \
	INCLUDE_COPROCESSOR \
	INCLUDE_COPROCESSOR_SHOW \
	INCLUDE_CPLUS \
	INCLUDE_CPLUS_DEMANGLER \
	INCLUDE_CPLUS_IOSTREAMS \
	INCLUDE_CPLUS_LANG \
	INCLUDE_CTORS_DTORS \
	INCLUDE_DATACOLLECTOR \
	INCLUDE_DEBUG \
	INCLUDE_DEBUG_SHELL_CMD \
	INCLUDE_DEVICE_MANAGER \
	INCLUDE_DIAB_INTRINSICS \
	INCLUDE_DISK_UTIL \
	INCLUDE_DISK_UTIL_SHELL_CMD \
	INCLUDE_DLL \
	INCLUDE_DLL_ARCH \
	INCLUDE_DMA_SYS \
	INCLUDE_DOSFS \
	INCLUDE_DOSFS_CACHE \
	INCLUDE_DOSFS_CHKDSK \
	INCLUDE_DOSFS_DIR_FIXED \
	INCLUDE_DOSFS_DIR_VFAT \
	INCLUDE_DOSFS_FAT \
	INCLUDE_DOSFS_FMT \
	INCLUDE_DOSFS_MAIN \
	INCLUDE_DOSFS_PRTMSG_LEVEL \
	INCLUDE_DOSFS_SHOW \
	INCLUDE_DOSFS_VOL_BIO_BUFFER_SIZE \
	INCLUDE_EDR_POLICY_HOOKS \
	INCLUDE_EDR_STUB \
	INCLUDE_EDR_SYSDBG_FLAG \
	INCLUDE_END \
	INCLUDE_END_COMMON \
	INCLUDE_END_ETHER_HDR \
	INCLUDE_ENV_VARS \
	INCLUDE_ERF \
	INCLUDE_ETHERNET \
	INCLUDE_EVENTPOINT \
	INCLUDE_EVENTPOINT_STUB \
	INCLUDE_EXC_HANDLING \
	INCLUDE_EXC_SHOW \
	INCLUDE_EXC_TASK \
	INCLUDE_FLOATING_POINT \
	INCLUDE_FORMATTED_IO \
	INCLUDE_FORMATTED_OUT_BASIC \
	INCLUDE_FP_TYPE \
	INCLUDE_FS_EVENT_UTIL \
	INCLUDE_FS_MONITOR \
	INCLUDE_FTP \
	INCLUDE_GENERICPHY \
	INCLUDE_GETADDRINFO_SYSCTL \
	INCLUDE_GETOPT \
	INCLUDE_GETSERVBYNAME \
	INCLUDE_GETSERVBYPORT \
	INCLUDE_GNU_INTRINSICS \
	INCLUDE_GTF \
	INCLUDE_GTF_TIMER_START \
	INCLUDE_HANDLE_SHOW \
	INCLUDE_HASH \
	INCLUDE_HOOKS \
	INCLUDE_HOOK_SHOW \
	INCLUDE_HOST_TBL \
	INCLUDE_HOST_TBL_SYSCTL \
	INCLUDE_HWMEM_ALLOC \
	INCLUDE_HW_FP_MREGS \
	INCLUDE_HW_FP_SHOW \
	INCLUDE_I2C_BUS \
	INCLUDE_IEEE_STATUS \
	INCLUDE_IFCONFIG \
	INCLUDE_INETLIB \
	INCLUDE_INTCTLR_LIB \
	INCLUDE_INTCTLR_SHOW \
	INCLUDE_IO_BASIC \
	INCLUDE_IO_FILE_SYSTEM \
	INCLUDE_IO_MISC \
	INCLUDE_IO_POSIX \
	INCLUDE_IO_REMOVABLE \
	INCLUDE_IO_RTP \
	INCLUDE_IO_SYSTEM \
	INCLUDE_IPAIP \
	INCLUDE_IPAIP_GLOBAL_CONFIGS \
	INCLUDE_IPATTACH \
	INCLUDE_IPCOM \
	INCLUDE_IPCOM_SHELL_CMD \
	INCLUDE_IPCOM_SYSLOGD_CMD \
	INCLUDE_IPCOM_USE_AUTH \
	INCLUDE_IPCOM_USE_ETHERNET \
	INCLUDE_IPCOM_USE_INET \
	INCLUDE_IPCOM_USR \
	INCLUDE_IPFTPC \
	INCLUDE_IPFTPS \
	INCLUDE_IPFTP_CMD \
	INCLUDE_IPIFCONFIG_CMD \
	INCLUDE_IPNET \
	INCLUDE_IPNETSTAT_CMD \
	INCLUDE_IPNET_IFCONFIG_1 \
	INCLUDE_IPNET_LOOPBACK_CONFIG \
	INCLUDE_IPNET_SOCKET \
	INCLUDE_IPNET_STACK \
	INCLUDE_IPNET_SYSCTL \
	INCLUDE_IPNET_USE_LOOPBACK \
	INCLUDE_IPNET_USE_ROUTESOCK \
	INCLUDE_IPNET_USE_SOCK_COMPAT \
	INCLUDE_IPPING_CMD \
	INCLUDE_IPPROXYARP \
	INCLUDE_IPROUTE_CMD \
	INCLUDE_IPTCP \
	INCLUDE_IPTELNETS \
	INCLUDE_IPTFTPC \
	INCLUDE_IPTFTP_CLIENT_CMD \
	INCLUDE_IPTFTP_COMMON \
	INCLUDE_IPV4 \
	INCLUDE_IPWRAP_GETADDRINFO \
	INCLUDE_IPWRAP_GETIFADDRS \
	INCLUDE_IPWRAP_GETSERVBYNAME \
	INCLUDE_IPWRAP_GETSERVBYPORT \
	INCLUDE_IPWRAP_IFCONFIG \
	INCLUDE_IPWRAP_IFSHOW \
	INCLUDE_IPWRAP_INETLIB \
	INCLUDE_IPWRAP_IPPROTO \
	INCLUDE_IPWRAP_NETSTAT \
	INCLUDE_IPWRAP_PING \
	INCLUDE_ISR_DEFER \
	INCLUDE_ISR_OBJECTS \
	INCLUDE_JOB_DEFER \
	INCLUDE_JOB_QUEUE \
	INCLUDE_JOB_TASK \
	INCLUDE_KERNEL \
	INCLUDE_KERNEL_ARCH \
	INCLUDE_LINKBUFPOOL \
	INCLUDE_LOADER \
	INCLUDE_LOADER_CODE \
	INCLUDE_LOADER_HOOKS \
	INCLUDE_LOGGING \
	INCLUDE_LSTLIB \
	INCLUDE_MBUF_UTIL1 \
	INCLUDE_MEMORY_CONFIG \
	INCLUDE_MEM_MGR_BASIC \
	INCLUDE_MEM_MGR_FULL \
	INCLUDE_MEM_MGR_INFO \
	INCLUDE_MEM_RTP \
	INCLUDE_MEM_SHOW \
	INCLUDE_MIB2_IF \
	INCLUDE_MICREL_PHY \
	INCLUDE_MII_BUS \
	INCLUDE_MMAP \
	INCLUDE_MMU_ARCH \
	INCLUDE_MMU_BASIC \
	INCLUDE_MMU_GLOBAL_MAP \
	INCLUDE_MODULE_MANAGER \
	INCLUDE_MODULE_SHELL_CMD \
	INCLUDE_MSG_Q \
	INCLUDE_MSG_Q_CREATE_DELETE \
	INCLUDE_MSG_Q_EVENTS \
	INCLUDE_MSG_Q_INFO \
	INCLUDE_MSG_Q_OPEN \
	INCLUDE_MSG_Q_SHOW \
	INCLUDE_MTD_CFISCS \
	INCLUDE_MUX \
	INCLUDE_MUX2 \
	INCLUDE_MUX2_OVER_END \
	INCLUDE_MUXTK \
	INCLUDE_MUXTK_OVER_END \
	INCLUDE_MUX_COMMON \
	INCLUDE_NETBUFLIB \
	INCLUDE_NETBUFPOOL \
	INCLUDE_NETMASK_GET \
	INCLUDE_NETPOOLSHOW \
	INCLUDE_NETSTAT \
	INCLUDE_NETWORK \
	INCLUDE_NET_BOOT \
	INCLUDE_NET_BOOT_CONFIG \
	INCLUDE_NET_DAEMON \
	INCLUDE_NET_DRV \
	INCLUDE_NET_HOST_SETUP \
	INCLUDE_NET_HOST_SHOW \
	INCLUDE_NET_INIT \
	INCLUDE_NET_REM_IO \
	INCLUDE_NET_SYSCTL \
	INCLUDE_OBJECT_SHOW \
	INCLUDE_OBJ_INFO \
	INCLUDE_OBJ_LIB \
	INCLUDE_OBJ_LIB_ARCH \
	INCLUDE_OBJ_OPEN \
	INCLUDE_OBJ_OWNERSHIP \
	INCLUDE_OFFSET_SYMBOLS \
	INCLUDE_OSM \
	INCLUDE_PARAM_SYS \
	INCLUDE_PG_MGR_BASIC \
	INCLUDE_PG_MGR_LIB \
	INCLUDE_PG_MGR_SHOW \
	INCLUDE_PG_POOL_LIB \
	INCLUDE_PG_POOL_PHYS_LIB \
	INCLUDE_PG_POOL_SHOW \
	INCLUDE_PG_POOL_VIRT_LIB \
	INCLUDE_PING \
	INCLUDE_PIPES \
	INCLUDE_PLB_BUS \
	INCLUDE_POOL \
	INCLUDE_POSIX_CLOCKS \
	INCLUDE_POSIX_DIRLIB \
	INCLUDE_POSIX_FS \
	INCLUDE_POSIX_TIMERS \
	INCLUDE_POSIX_TIMER_SHOW \
	INCLUDE_PROTECT_TASK_STACK \
	INCLUDE_PTYDRV \
	INCLUDE_Q_FIFO \
	INCLUDE_Q_PRI_BMAP \
	INCLUDE_Q_PRI_DELTA \
	INCLUDE_Q_PRI_LIST \
	INCLUDE_RAWFS \
	INCLUDE_RBUFF \
	INCLUDE_RBUFF_SHOW \
	INCLUDE_REBOOT_HOOKS \
	INCLUDE_REMLIB \
	INCLUDE_REMLIB_SYSCTL \
	INCLUDE_RNG_BUF \
	INCLUDE_RTP \
	INCLUDE_RTP_APPL_INIT_BOOTLINE \
	INCLUDE_RTP_APPL_USER \
	INCLUDE_RTP_ARCH \
	INCLUDE_RTP_DEBUG \
	INCLUDE_RTP_DEBUG_COMMAND \
	INCLUDE_RTP_HOOKS \
	INCLUDE_RTP_SHELL_C \
	INCLUDE_RTP_SHELL_CMD \
	INCLUDE_RTP_SHOW \
	INCLUDE_RTP_SHOW_SHELL_CMD \
	INCLUDE_SC_IOS \
	INCLUDE_SC_KERNEL \
	INCLUDE_SC_MMAN \
	INCLUDE_SC_POSIX \
	INCLUDE_SC_SD \
	INCLUDE_SC_SHL \
	INCLUDE_SC_SOCKLIB \
	INCLUDE_SC_SYSCTL \
	INCLUDE_SD_BUS \
	INCLUDE_SELECT \
	INCLUDE_SELECT_SUPPORT \
	INCLUDE_SEM_BINARY \
	INCLUDE_SEM_BINARY_CREATE \
	INCLUDE_SEM_COUNTING \
	INCLUDE_SEM_COUNTING_CREATE \
	INCLUDE_SEM_DELETE \
	INCLUDE_SEM_EVENTS \
	INCLUDE_SEM_EXCHANGE \
	INCLUDE_SEM_INFO \
	INCLUDE_SEM_LIB \
	INCLUDE_SEM_MUTEX \
	INCLUDE_SEM_MUTEX_CREATE \
	INCLUDE_SEM_OPEN \
	INCLUDE_SEM_READ_WRITE \
	INCLUDE_SEM_READ_WRITE_CREATE \
	INCLUDE_SEM_SHOW \
	INCLUDE_SEQ_TIMESTAMP \
	INCLUDE_SHARED_DATA \
	INCLUDE_SHARED_DATA_SHOW \
	INCLUDE_SHARED_DATA_SHOW_SHELL_CMD \
	INCLUDE_SHELL \
	INCLUDE_SHELL_BANNER \
	INCLUDE_SHELL_CORE \
	INCLUDE_SHELL_EMACS_MODE \
	INCLUDE_SHELL_INTERP_C \
	INCLUDE_SHELL_INTERP_CMD \
	INCLUDE_SHELL_VI_MODE \
	INCLUDE_SHL \
	INCLUDE_SHL_SHELL_CMD \
	INCLUDE_SHL_SHOW \
	INCLUDE_SHOW_ROUTINES \
	INCLUDE_SIGEVENT \
	INCLUDE_SIGNALS \
	INCLUDE_SIGNAL_ARCH \
	INCLUDE_SIO \
	INCLUDE_SIO_UTILS \
	INCLUDE_SLL \
	INCLUDE_SOCKLIB \
	INCLUDE_SPINLOCK \
	INCLUDE_SPINLOCK_ISR_ND \
	INCLUDE_SPI_BUS \
	INCLUDE_STANDALONE_SYM_TBL \
	INCLUDE_STARTUP_SCRIPT \
	INCLUDE_STAT_SYM_TBL \
	INCLUDE_STDIO \
	INCLUDE_STDIO_SHOW \
	INCLUDE_SV_DATACOLLECTOR \
	INCLUDE_SYM_SHELL_CMD \
	INCLUDE_SYM_TBL \
	INCLUDE_SYM_TBL_INIT \
	INCLUDE_SYM_TBL_SHOW \
	INCLUDE_SYSCALL_HOOKS \
	INCLUDE_SYSCLK_INIT \
	INCLUDE_SYSCTL \
	INCLUDE_SYSCTL_HW \
	INCLUDE_SYSDBG_FLAG \
	INCLUDE_SYSHW_INIT \
	INCLUDE_SYSHW_INIT2 \
	INCLUDE_SYS_MEM_MGMT \
	INCLUDE_SYS_START \
	INCLUDE_TAR \
	INCLUDE_TASK_CREATE_DELETE \
	INCLUDE_TASK_CREATE_HOOKS \
	INCLUDE_TASK_HOOKS \
	INCLUDE_TASK_HOOKS_SHOW \
	INCLUDE_TASK_INFO \
	INCLUDE_TASK_LIST \
	INCLUDE_TASK_OPEN \
	INCLUDE_TASK_RESTART \
	INCLUDE_TASK_SHELL_CMD \
	INCLUDE_TASK_SHOW \
	INCLUDE_TASK_STACK_ALLOC \
	INCLUDE_TASK_STACK_NO_EXEC \
	INCLUDE_TASK_SWAP_HOOKS \
	INCLUDE_TASK_SWITCH_HOOKS \
	INCLUDE_TASK_UTIL \
	INCLUDE_TASK_VARS \
	INCLUDE_TELNET_CLIENT \
	INCLUDE_TFFS \
	INCLUDE_TFFS_MOUNT \
	INCLUDE_TFFS_SHOW \
	INCLUDE_TIMER_OPEN \
	INCLUDE_TIMER_SYS \
	INCLUDE_TIMER_SYS_DELAY \
	INCLUDE_TIMESTAMP \
	INCLUDE_TIMEX \
	INCLUDE_TIP \
	INCLUDE_TIP_CMD \
	INCLUDE_TLS \
	INCLUDE_TLS_LOADER_SUPPORT \
	INCLUDE_TL_FTL \
	INCLUDE_TRIGGERING \
	INCLUDE_TRIGGER_SHOW \
	INCLUDE_TRIG_DATACOLLECTOR \
	INCLUDE_TTY_DEV \
	INCLUDE_TYLIB \
	INCLUDE_UNLOADER \
	INCLUDE_UNLOADER_SHELL_CMD \
	INCLUDE_USER_APPL \
	INCLUDE_USE_NATIVE_SHELL \
	INCLUDE_VFP \
	INCLUDE_VM_INVTBL \
	INCLUDE_VM_RTP \
	INCLUDE_VM_SHOW \
	INCLUDE_VM_SHOW_SHELL_CMD \
	INCLUDE_VXBUS \
	INCLUDE_VXBUS_ACTIVATE \
	INCLUDE_VXBUS_DEVICE_CONNECT \
	INCLUDE_VXBUS_DEV_INIT \
	INCLUDE_VXBUS_INIT \
	INCLUDE_VXBUS_SHOW \
	INCLUDE_VXB_AUX_CLK \
	INCLUDE_VXB_SYS_CLK \
	INCLUDE_VXB_TIMESTAMP \
	INCLUDE_VXDBG \
	INCLUDE_VXDBG_HOOK \
	INCLUDE_VXDBG_MODULE \
	INCLUDE_VXDBG_RUNCTRL \
	INCLUDE_VXEVENTS \
	INCLUDE_VXIPI \
	INCLUDE_VXMEMPROBE_INIT \
	INCLUDE_VXMUX_MBLK \
	INCLUDE_VXMUX_NULLBUFPOOL \
	INCLUDE_VX_NATIVE_SCHEDULER \
	INCLUDE_VX_TRADITIONAL_SCHEDULER \
	INCLUDE_WATCHDOGS \
	INCLUDE_WATCHDOGS_CREATE_DELETE \
	INCLUDE_WATCHDOGS_SHOW \
	INCLUDE_WB_RUNTIME_SUPPORT \
	INCLUDE_WDB \
	INCLUDE_WDB_COMM_NETWORK \
	INCLUDE_WDB_DIRECT_CALL \
	INCLUDE_WDB_EVENTS \
	INCLUDE_WDB_GOPHER \
	INCLUDE_WDB_MDL_SYM_SYNC \
	INCLUDE_WDB_POST_KERNEL_INIT \
	INCLUDE_WDB_RTP \
	INCLUDE_WDB_RTP_CONTROL \
	INCLUDE_WDB_TASK \
	INCLUDE_WDB_TASK_HOOKS \
	INCLUDE_WDB_TSFS \
	INCLUDE_WINDVIEW \
	INCLUDE_WINDVIEW_CLASS \
	INCLUDE_WVUPLOAD_FILE \
	INCLUDE_WVUPLOAD_TSFSSOCK \
	INCLUDE_XBD \
	INCLUDE_XBD_BLK_DEV \
	INCLUDE_XBD_PART_LIB \
	INCLUDE_XDR \
	INIT_HWMEMPOOL_GLOBAL \
	VXBUS_TABLE_CONFIG

MANAGED_LIBS = libspl.a libtipc.a
COMPONENT_LIBS = libspl.a

PROJECT_LINK_SYMDEFS = 


include $(TGT_DIR)/h/make/defs.project


## project-configuration info


## build-configuration info

ifeq ($(BUILD_SPEC),default)
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CFLAGS_AS_PROJECT = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xc-new -Xdialect-c89 -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xlit-auto-off -Wa,-Xenable-coprocessor-vfp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -ei1518,4177,4223,4301,4550,5409,1606 -ei4193,4826,4381,4237,1573,4007,4082,4177,4223,4260,4550,5361,5828,2273,5387,5388 -ei1522,4092,4111,4152,4167,4171,4174,4186,4188,4191,4192,4223,4231,4236,4284,4375,4494,4513,5152,5457 -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/diab_standard -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -Xmake-dependency -w
RELEASE_CMD      = bootrom.bin
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
_USER_CFLAGS     =  -I $(PRJ_DIR)
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_rom)
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CFLAGS_AS_PROJECT = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xc-new -Xdialect-c89 -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xlit-auto-off -Wa,-Xenable-coprocessor-vfp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -ei1518,4177,4223,4301,4550,5409,1606 -ei4193,4826,4381,4237,1573,4007,4082,4177,4223,4260,4550,5361,5828,2273,5387,5388 -ei1522,4092,4111,4152,4167,4171,4174,4186,4188,4191,4192,4223,4231,4236,4284,4375,4494,4513,5152,5457 -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/diab_standard -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -Xmake-dependency -w
RELEASE_CMD      = bootrom.bin
ROM_SIZE         = 00200000 # number of bytes of ROM space
ROM_TEXT_ADRS    = 0fc00000 # ROM entry address
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
HEX_FLAGS        = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romCompress)
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CFLAGS_AS_PROJECT = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xc-new -Xdialect-c89 -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xlit-auto-off -Wa,-Xenable-coprocessor-vfp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -ei1518,4177,4223,4301,4550,5409,1606 -ei4193,4826,4381,4237,1573,4007,4082,4177,4223,4260,4550,5361,5828,2273,5387,5388 -ei1522,4092,4111,4152,4167,4171,4174,4186,4188,4191,4192,4223,4231,4236,4284,4375,4494,4513,5152,5457 -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/diab_standard -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -Xmake-dependency -w
RELEASE_CMD      = bootrom.bin
ROM_SIZE         = 00200000 # number of bytes of ROM space
ROM_TEXT_ADRS    = 0fc00000 # ROM entry address
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
HEX_FLAGS        = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romResident)
AS               = dcc
BOOT_EXTRA       = 
CC               = dcc
CFLAGS_AS_PROJECT = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xc-new -Xdialect-c89 -Xsize-opt -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -Xpreprocess-assembly -Xcpp-no-space -Wa,-Xlit-auto-off -Wa,-Xenable-coprocessor-vfp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -tARMV7LV:vxworks69 -W:c:,-Xclib-optim-off -Xansi -Xlocal-data-area-static-only -W:c++:.CPP -Xfp-fast -Xsize-opt -W:c:,-Xmismatch-warning=2 -ew1554,1551,1552,1086,1047,1547 -ei1516,1643,1604 -ei1518,4177,4223,4301,4550,5409,1606 -ei4193,4826,4381,4237,1573,4007,4082,4177,4223,4260,4550,5361,5828,2273,5387,5388 -ei1522,4092,4111,4152,4167,4171,4174,4186,4188,4191,4192,4223,4231,4236,4284,4375,4494,4513,5152,5457 -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=diab -DTOOL=diab -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA8 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/tcf_agent-0.3/agent -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-0.3/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h -@./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/diab_standard -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/diab -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/diab -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -Xmake-dependency -w
RELEASE_CMD      = bootrom.bin
ROM_SIZE         = 00200000 # number of bytes of ROM space
ROM_TEXT_ADRS    = 0fc00000 # ROM entry address
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
HEX_FLAGS        = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

# override make definitions only below this line


# override make definitions only above this line

include $(TGT_DIR)/h/make/rules.project


## build-configuration info

ifeq ($(BUILD_SPEC),default)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

fifo.o:  $(PRJ_DIR)/fifo.c 
	$(RM) fifo.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/fifo.c

PlcSpiTest.o:  $(PRJ_DIR)/PlcSpiTest.c 
	$(RM) PlcSpiTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PlcSpiTest.c

comtest.o:  $(PRJ_DIR)/comtest.c 
	$(RM) comtest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/comtest.c

pulsetest.o:  $(PRJ_DIR)/pulsetest.c 
	$(RM) pulsetest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/pulsetest.c
endif

ifeq ($(BUILD_SPEC),default_rom)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

fifo.o:  $(PRJ_DIR)/fifo.c 
	$(RM) fifo.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/fifo.c

PlcSpiTest.o:  $(PRJ_DIR)/PlcSpiTest.c 
	$(RM) PlcSpiTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PlcSpiTest.c

comtest.o:  $(PRJ_DIR)/comtest.c 
	$(RM) comtest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/comtest.c

pulsetest.o:  $(PRJ_DIR)/pulsetest.c 
	$(RM) pulsetest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/pulsetest.c
endif

ifeq ($(BUILD_SPEC),default_romCompress)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

fifo.o:  $(PRJ_DIR)/fifo.c 
	$(RM) fifo.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/fifo.c

PlcSpiTest.o:  $(PRJ_DIR)/PlcSpiTest.c 
	$(RM) PlcSpiTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PlcSpiTest.c

comtest.o:  $(PRJ_DIR)/comtest.c 
	$(RM) comtest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/comtest.c

pulsetest.o:  $(PRJ_DIR)/pulsetest.c 
	$(RM) pulsetest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/pulsetest.c
endif

ifeq ($(BUILD_SPEC),default_romResident)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

fifo.o:  $(PRJ_DIR)/fifo.c 
	$(RM) fifo.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/fifo.c

PlcSpiTest.o:  $(PRJ_DIR)/PlcSpiTest.c 
	$(RM) PlcSpiTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PlcSpiTest.c

comtest.o:  $(PRJ_DIR)/comtest.c 
	$(RM) comtest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/comtest.c

pulsetest.o:  $(PRJ_DIR)/pulsetest.c 
	$(RM) pulsetest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/pulsetest.c
endif


## user defined rules

vxWorks.res_rom.bin: vxWorks.res_rom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks.res_rom $@

vxWorks_rom.bin: vxWorks_rom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks_rom $@

romStart.o : $(TGT_DIR)/config/comps/src/romStart.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

bootrom.bin: bootrom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary bootrom $@

bootrom_uncmp.bin: bootrom_uncmp
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary bootrom_uncmp $@

romInit.o : $(BSP_DIR)/romInit.s
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

linkSyms.o : $(PRJ_DIR)/linkSyms.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/linkSyms.c -o $@

bootrom_res.bin: bootrom_res
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary bootrom_res $@

sysLib.o : $(BSP_DIR)/sysLib.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(BSP_DIR)/sysLib.c -o $@

sysALib.o : $(BSP_DIR)/sysALib.s
	$(AS) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(BSP_DIR)/sysALib.s -o $@

vxWorks.st_rom.bin: vxWorks.st_rom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks.st_rom $@

vxWorks.res_rom_nosym.bin: vxWorks.res_rom_nosym
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks.res_rom_nosym $@

prjConfig.o : $(PRJ_DIR)/prjConfig.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/prjConfig.c -o $@


src_build :

src_depend :

$(PRJ_FULL_PATH)/compObjs.lst : $(PRJ_MAKEFILE)
	@ $(RM) $@
	@ touch $@

src_clean :
	@ $(RM) compObjs.lst
